#!/usr/bin/perl -w

use strict;

if (@ARGV != 1) {
  die "\nUsage: GetNucFrequency.pl FastaFile > Outfile\n\n";
}


my $file1=shift;
my @array=
('A','G','AA','AT','AG','AC','TA','TG','TC','GG','GC','CG','AAA','AAT','AAG','AAC','ATA','ATG','ATC','AGA','AGT','AGG','AGC','ACA','ACG','ACC','TAA','TAG','TAC','TTG','TTC','TGA','TGG','TGC','TCG','TCC','GAG','GAC','GTG','GGG','GGC','GCG','CAG','CGG','AAAA','AAAT','AAAG','AAAC','AATA','AATT','AATG','AATC','AAGA','AAGT','AAGG','AAGC','AACA','AACT','AACG','AACC','ATAA','ATAT','ATAG','ATAC','ATTA','ATTG','ATTC','ATGA','ATGT','ATGG','ATGC','ATCA','ATCT','ATCG','ATCC','AGAA','AGAG','AGAC','AGTA','AGTG','AGTC','AGGA','AGGT','AGGG','AGGC','AGCA','AGCT','AGCG','AGCC','ACAA','ACAG','ACAC','ACTA','ACTG','ACTC','ACGA','ACGT','ACGG','ACGC','ACCA','ACCG','ACCC','TAAA','TAAG','TAAC','TATA','TATG','TATC','TAGA','TAGG','TAGC','TACA','TACG','TACC','TTAA','TTAG','TTAC','TTTG','TTTC','TTGA','TTGG','TTGC','TTCA','TTCG','TTCC','TGAG','TGAC','TGTG','TGTC','TGGA','TGGG','TGGC','TGCA','TGCG','TGCC','TCAG','TCAC','TCTG','TCTC','TCGA','TCGG','TCGC','TCCG','TCCC','GAAG','GAAC','GATG','GATC','GAGG','GAGC','GACG','GACC','GTAG','GTAC','GTTG','GTGG','GTGC','GTCG','GTCC','GGAG','GGTG','GGGG','GGGC','GGCG','GGCC','GCAG','GCTG','GCGG','GCGC','GCCG','CAAG','CATG','CAGG','CACG','CTAG','CTGG','CTCG','CGGG','CGCG','CCGG','AAAAA','AAAAT','AAAAG','AAAAC','AAATA','AAATT','AAATG','AAATC','AAAGA','AAAGT','AAAGG','AAAGC','AAACA','AAACT','AAACG','AAACC','AATAA','AATAT','AATAG','AATAC','AATTA','AATTG','AATTC','AATGA','AATGT','AATGG','AATGC','AATCA','AATCT','AATCG','AATCC','AAGAA','AAGAT','AAGAG','AAGAC','AAGTA','AAGTT','AAGTG','AAGTC','AAGGA','AAGGT','AAGGG','AAGGC','AAGCA','AAGCT','AAGCG','AAGCC','AACAA','AACAT','AACAG','AACAC','AACTA','AACTG','AACTC','AACGA','AACGT','AACGG','AACGC','AACCA','AACCT','AACCG','AACCC','ATAAA','ATAAT','ATAAG','ATAAC','ATATA','ATATG','ATATC','ATAGA','ATAGT','ATAGG','ATAGC','ATACA','ATACT','ATACG','ATACC','ATTAA','ATTAG','ATTAC','ATTTA','ATTTG','ATTTC','ATTGA','ATTGT','ATTGG','ATTGC','ATTCA','ATTCT','ATTCG','ATTCC','ATGAA','ATGAT','ATGAG','ATGAC','ATGTA','ATGTG','ATGTC','ATGGA','ATGGT','ATGGG','ATGGC','ATGCA','ATGCT','ATGCG','ATGCC','ATCAA','ATCAG','ATCAC','ATCTA','ATCTG','ATCTC','ATCGA','ATCGT','ATCGG','ATCGC','ATCCA','ATCCT','ATCCG','ATCCC','AGAAA','AGAAG','AGAAC','AGATA','AGATG','AGATC','AGAGA','AGAGT','AGAGG','AGAGC','AGACA','AGACT','AGACG','AGACC','AGTAA','AGTAG','AGTAC','AGTTA','AGTTG','AGTTC','AGTGA','AGTGT','AGTGG','AGTGC','AGTCA','AGTCG','AGTCC','AGGAA','AGGAG','AGGAC','AGGTA','AGGTG','AGGTC','AGGGA','AGGGT','AGGGG','AGGGC','AGGCA','AGGCT','AGGCG','AGGCC','AGCAA','AGCAG','AGCAC','AGCTA','AGCTG','AGCTC','AGCGA','AGCGT','AGCGG','AGCGC','AGCCA','AGCCG','AGCCC','ACAAA','ACAAG','ACAAC','ACATA','ACATG','ACATC','ACAGA','ACAGT','ACAGG','ACAGC','ACACA','ACACG','ACACC','ACTAA','ACTAG','ACTAC','ACTTA','ACTTG','ACTTC','ACTGA','ACTGG','ACTGC','ACTCA','ACTCG','ACTCC','ACGAA','ACGAG','ACGAC','ACGTA','ACGTG','ACGTC','ACGGA','ACGGT','ACGGG','ACGGC','ACGCA','ACGCG','ACGCC','ACCAA','ACCAG','ACCAC','ACCTA','ACCTG','ACCTC','ACCGA','ACCGG','ACCGC','ACCCA','ACCCG','ACCCC','TAAAA','TAAAG','TAAAC','TAATA','TAATG','TAATC','TAAGA','TAAGG','TAAGC','TAACA','TAACG','TAACC','TATAA','TATAG','TATAC','TATTG','TATTC','TATGA','TATGG','TATGC','TATCA','TATCG','TATCC','TAGAA','TAGAG','TAGAC','TAGTA','TAGTG','TAGTC','TAGGA','TAGGG','TAGGC','TAGCA','TAGCG','TAGCC','TACAA','TACAG','TACAC','TACTG','TACTC','TACGA','TACGG','TACGC','TACCA','TACCG','TACCC','TTAAA','TTAAG','TTAAC','TTATG','TTATC','TTAGA','TTAGG','TTAGC','TTACA','TTACG','TTACC','TTTAG','TTTAC','TTTTG','TTTTC','TTTGA','TTTGG','TTTGC','TTTCA','TTTCG','TTTCC','TTGAA','TTGAG','TTGAC','TTGTG','TTGTC','TTGGA','TTGGG','TTGGC','TTGCA','TTGCG','TTGCC','TTCAG','TTCAC','TTCTG','TTCTC','TTCGA','TTCGG','TTCGC','TTCCA','TTCCG','TTCCC','TGAAG','TGAAC','TGATG','TGATC','TGAGA','TGAGG','TGAGC','TGACA','TGACG','TGACC','TGTAG','TGTAC','TGTTG','TGTTC','TGTGA','TGTGG','TGTGC','TGTCG','TGTCC','TGGAG','TGGAC','TGGTG','TGGTC','TGGGA','TGGGG','TGGGC','TGGCA','TGGCG','TGGCC','TGCAG','TGCAC','TGCTG','TGCTC','TGCGA','TGCGG','TGCGC','TGCCG','TGCCC','TCAAG','TCAAC','TCATG','TCATC','TCAGA','TCAGG','TCAGC','TCACG','TCACC','TCTAG','TCTAC','TCTTG','TCTTC','TCTGG','TCTGC','TCTCG','TCTCC','TCGAG','TCGAC','TCGTG','TCGTC','TCGGA','TCGGG','TCGGC','TCGCG','TCGCC','TCCAG','TCCAC','TCCTG','TCCTC','TCCGG','TCCGC','TCCCG','TCCCC','GAAAG','GAAAC','GAATG','GAATC','GAAGG','GAAGC','GAACG','GAACC','GATAG','GATAC','GATTG','GATGG','GATGC','GATCG','GATCC','GAGAG','GAGAC','GAGTG','GAGTC','GAGGG','GAGGC','GAGCG','GAGCC','GACAG','GACAC','GACTG','GACGG','GACGC','GACCG','GACCC','GTAAG','GTAAC','GTATG','GTAGG','GTAGC','GTACG','GTACC','GTTAG','GTTTG','GTTGG','GTTGC','GTTCG','GTTCC','GTGAG','GTGAC','GTGTG','GTGGG','GTGGC','GTGCG','GTGCC','GTCAG','GTCTG','GTCGG','GTCGC','GTCCG','GTCCC','GGAAG','GGATG','GGAGG','GGAGC','GGACG','GGACC','GGTAG','GGTTG','GGTGG','GGTGC','GGTCG','GGGAG','GGGTG','GGGGG','GGGGC','GGGCG','GGGCC','GGCAG','GGCTG','GGCGG','GGCGC','GGCCG','GCAAG','GCATG','GCAGG','GCAGC','GCACG','GCTAG','GCTTG','GCTGG','GCTCG','GCGAG','GCGTG','GCGGG','GCGGC','GCGCG','GCCAG','GCCTG','GCCGG','GCCCG','CAAAG','CAATG','CAAGG','CAACG','CATAG','CATGG','CATCG','CAGAG','CAGTG','CAGGG','CAGCG','CACAG','CACGG','CACCG','CTAAG','CTAGG','CTACG','CTTGG','CTTCG','CTGAG','CTGGG','CTGCG','CTCGG','CTCCG','CGAGG','CGACG','CGTGG','CGGGG','CGGCG','CGCGG','CCAGG','CCGGG','AAAAAA','AAAAAT','AAAAAG','AAAAAC','AAAATA','AAAATT','AAAATG','AAAATC','AAAAGA','AAAAGT','AAAAGG','AAAAGC','AAAACA','AAAACT','AAAACG','AAAACC','AAATAA','AAATAT','AAATAG','AAATAC','AAATTA','AAATTT','AAATTG','AAATTC','AAATGA','AAATGT','AAATGG','AAATGC','AAATCA','AAATCT','AAATCG','AAATCC','AAAGAA','AAAGAT','AAAGAG','AAAGAC','AAAGTA','AAAGTT','AAAGTG','AAAGTC','AAAGGA','AAAGGT','AAAGGG','AAAGGC','AAAGCA','AAAGCT','AAAGCG','AAAGCC','AAACAA','AAACAT','AAACAG','AAACAC','AAACTA','AAACTT','AAACTG','AAACTC','AAACGA','AAACGT','AAACGG','AAACGC','AAACCA','AAACCT','AAACCG','AAACCC','AATAAA','AATAAT','AATAAG','AATAAC','AATATA','AATATT','AATATG','AATATC','AATAGA','AATAGT','AATAGG','AATAGC','AATACA','AATACT','AATACG','AATACC','AATTAA','AATTAT','AATTAG','AATTAC','AATTTA','AATTTG','AATTTC','AATTGA','AATTGT','AATTGG','AATTGC','AATTCA','AATTCT','AATTCG','AATTCC','AATGAA','AATGAT','AATGAG','AATGAC','AATGTA','AATGTT','AATGTG','AATGTC','AATGGA','AATGGT','AATGGG','AATGGC','AATGCA','AATGCT','AATGCG','AATGCC','AATCAA','AATCAT','AATCAG','AATCAC','AATCTA','AATCTT','AATCTG','AATCTC','AATCGA','AATCGT','AATCGG','AATCGC','AATCCA','AATCCT','AATCCG','AATCCC','AAGAAA','AAGAAT','AAGAAG','AAGAAC','AAGATA','AAGATG','AAGATC','AAGAGA','AAGAGT','AAGAGG','AAGAGC','AAGACA','AAGACT','AAGACG','AAGACC','AAGTAA','AAGTAT','AAGTAG','AAGTAC','AAGTTA','AAGTTG','AAGTTC','AAGTGA','AAGTGT','AAGTGG','AAGTGC','AAGTCA','AAGTCT','AAGTCG','AAGTCC','AAGGAA','AAGGAT','AAGGAG','AAGGAC','AAGGTA','AAGGTT','AAGGTG','AAGGTC','AAGGGA','AAGGGT','AAGGGG','AAGGGC','AAGGCA','AAGGCT','AAGGCG','AAGGCC','AAGCAA','AAGCAT','AAGCAG','AAGCAC','AAGCTA','AAGCTT','AAGCTG','AAGCTC','AAGCGA','AAGCGT','AAGCGG','AAGCGC','AAGCCA','AAGCCT','AAGCCG','AAGCCC','AACAAA','AACAAT','AACAAG','AACAAC','AACATA','AACATG','AACATC','AACAGA','AACAGT','AACAGG','AACAGC','AACACA','AACACT','AACACG','AACACC','AACTAA','AACTAT','AACTAG','AACTAC','AACTTA','AACTTG','AACTTC','AACTGA','AACTGT','AACTGG','AACTGC','AACTCA','AACTCT','AACTCG','AACTCC','AACGAA','AACGAT','AACGAG','AACGAC','AACGTA','AACGTT','AACGTG','AACGTC','AACGGA','AACGGT','AACGGG','AACGGC','AACGCA','AACGCT','AACGCG','AACGCC','AACCAA','AACCAT','AACCAG','AACCAC','AACCTA','AACCTG','AACCTC','AACCGA','AACCGT','AACCGG','AACCGC','AACCCA','AACCCT','AACCCG','AACCCC','ATAAAA','ATAAAT','ATAAAG','ATAAAC','ATAATA','ATAATG','ATAATC','ATAAGA','ATAAGT','ATAAGG','ATAAGC','ATAACA','ATAACT','ATAACG','ATAACC','ATATAA','ATATAT','ATATAG','ATATAC','ATATTA','ATATTG','ATATTC','ATATGA','ATATGT','ATATGG','ATATGC','ATATCA','ATATCT','ATATCG','ATATCC','ATAGAA','ATAGAT','ATAGAG','ATAGAC','ATAGTA','ATAGTG','ATAGTC','ATAGGA','ATAGGT','ATAGGG','ATAGGC','ATAGCA','ATAGCT','ATAGCG','ATAGCC','ATACAA','ATACAT','ATACAG','ATACAC','ATACTA','ATACTG','ATACTC','ATACGA','ATACGT','ATACGG','ATACGC','ATACCA','ATACCT','ATACCG','ATACCC','ATTAAA','ATTAAT','ATTAAG','ATTAAC','ATTATA','ATTATG','ATTATC','ATTAGA','ATTAGT','ATTAGG','ATTAGC','ATTACA','ATTACT','ATTACG','ATTACC','ATTTAA','ATTTAG','ATTTAC','ATTTTA','ATTTTG','ATTTTC','ATTTGA','ATTTGT','ATTTGG','ATTTGC','ATTTCA','ATTTCT','ATTTCG','ATTTCC','ATTGAA','ATTGAT','ATTGAG','ATTGAC','ATTGTA','ATTGTG','ATTGTC','ATTGGA','ATTGGT','ATTGGG','ATTGGC','ATTGCA','ATTGCT','ATTGCG','ATTGCC','ATTCAA','ATTCAT','ATTCAG','ATTCAC','ATTCTA','ATTCTG','ATTCTC','ATTCGA','ATTCGT','ATTCGG','ATTCGC','ATTCCA','ATTCCT','ATTCCG','ATTCCC','ATGAAA','ATGAAG','ATGAAC','ATGATA','ATGATG','ATGATC','ATGAGA','ATGAGT','ATGAGG','ATGAGC','ATGACA','ATGACT','ATGACG','ATGACC','ATGTAA','ATGTAG','ATGTAC','ATGTTA','ATGTTG','ATGTTC','ATGTGA','ATGTGT','ATGTGG','ATGTGC','ATGTCA','ATGTCT','ATGTCG','ATGTCC','ATGGAA','ATGGAT','ATGGAG','ATGGAC','ATGGTA','ATGGTG','ATGGTC','ATGGGA','ATGGGT','ATGGGG','ATGGGC','ATGGCA','ATGGCT','ATGGCG','ATGGCC','ATGCAA','ATGCAT','ATGCAG','ATGCAC','ATGCTA','ATGCTG','ATGCTC','ATGCGA','ATGCGT','ATGCGG','ATGCGC','ATGCCA','ATGCCT','ATGCCG','ATGCCC','ATCAAA','ATCAAG','ATCAAC','ATCATA','ATCATG','ATCATC','ATCAGA','ATCAGT','ATCAGG','ATCAGC','ATCACA','ATCACT','ATCACG','ATCACC','ATCTAA','ATCTAG','ATCTAC','ATCTTA','ATCTTG','ATCTTC','ATCTGA','ATCTGT','ATCTGG','ATCTGC','ATCTCA','ATCTCT','ATCTCG','ATCTCC','ATCGAA','ATCGAT','ATCGAG','ATCGAC','ATCGTA','ATCGTG','ATCGTC','ATCGGA','ATCGGT','ATCGGG','ATCGGC','ATCGCA','ATCGCT','ATCGCG','ATCGCC','ATCCAA','ATCCAG','ATCCAC','ATCCTA','ATCCTG','ATCCTC','ATCCGA','ATCCGT','ATCCGG','ATCCGC','ATCCCA','ATCCCT','ATCCCG','ATCCCC','AGAAAA','AGAAAG','AGAAAC','AGAATA','AGAATG','AGAATC','AGAAGA','AGAAGT','AGAAGG','AGAAGC','AGAACA','AGAACT','AGAACG','AGAACC','AGATAA','AGATAG','AGATAC','AGATTA','AGATTG','AGATTC','AGATGA','AGATGT','AGATGG','AGATGC','AGATCA','AGATCT','AGATCG','AGATCC','AGAGAA','AGAGAG','AGAGAC','AGAGTA','AGAGTG','AGAGTC','AGAGGA','AGAGGT','AGAGGG','AGAGGC','AGAGCA','AGAGCT','AGAGCG','AGAGCC','AGACAA','AGACAG','AGACAC','AGACTA','AGACTG','AGACTC','AGACGA','AGACGT','AGACGG','AGACGC','AGACCA','AGACCT','AGACCG','AGACCC','AGTAAA','AGTAAG','AGTAAC','AGTATA','AGTATG','AGTATC','AGTAGA','AGTAGT','AGTAGG','AGTAGC','AGTACA','AGTACT','AGTACG','AGTACC','AGTTAA','AGTTAG','AGTTAC','AGTTTA','AGTTTG','AGTTTC','AGTTGA','AGTTGT','AGTTGG','AGTTGC','AGTTCA','AGTTCG','AGTTCC','AGTGAA','AGTGAG','AGTGAC','AGTGTA','AGTGTG','AGTGTC','AGTGGA','AGTGGT','AGTGGG','AGTGGC','AGTGCA','AGTGCT','AGTGCG','AGTGCC','AGTCAA','AGTCAG','AGTCAC','AGTCTA','AGTCTG','AGTCTC','AGTCGA','AGTCGT','AGTCGG','AGTCGC','AGTCCA','AGTCCT','AGTCCG','AGTCCC','AGGAAA','AGGAAG','AGGAAC','AGGATA','AGGATG','AGGATC','AGGAGA','AGGAGT','AGGAGG','AGGAGC','AGGACA','AGGACG','AGGACC','AGGTAA','AGGTAG','AGGTAC','AGGTTA','AGGTTG','AGGTTC','AGGTGA','AGGTGT','AGGTGG','AGGTGC','AGGTCA','AGGTCG','AGGTCC','AGGGAA','AGGGAG','AGGGAC','AGGGTA','AGGGTG','AGGGTC','AGGGGA','AGGGGT','AGGGGG','AGGGGC','AGGGCA','AGGGCT','AGGGCG','AGGGCC','AGGCAA','AGGCAG','AGGCAC','AGGCTA','AGGCTG','AGGCTC','AGGCGA','AGGCGT','AGGCGG','AGGCGC','AGGCCA','AGGCCT','AGGCCG','AGGCCC','AGCAAA','AGCAAG','AGCAAC','AGCATA','AGCATG','AGCATC','AGCAGA','AGCAGT','AGCAGG','AGCAGC','AGCACA','AGCACG','AGCACC','AGCTAA','AGCTAG','AGCTAC','AGCTTA','AGCTTG','AGCTTC','AGCTGA','AGCTGT','AGCTGG','AGCTGC','AGCTCA','AGCTCG','AGCTCC','AGCGAA','AGCGAG','AGCGAC','AGCGTA','AGCGTG','AGCGTC','AGCGGA','AGCGGT','AGCGGG','AGCGGC','AGCGCA','AGCGCT','AGCGCG','AGCGCC','AGCCAA','AGCCAG','AGCCAC','AGCCTA','AGCCTG','AGCCTC','AGCCGA','AGCCGT','AGCCGG','AGCCGC','AGCCCA','AGCCCG','AGCCCC','ACAAAA','ACAAAG','ACAAAC','ACAATA','ACAATG','ACAATC','ACAAGA','ACAAGT','ACAAGG','ACAAGC','ACAACA','ACAACG','ACAACC','ACATAA','ACATAG','ACATAC','ACATTA','ACATTG','ACATTC','ACATGA','ACATGT','ACATGG','ACATGC','ACATCA','ACATCG','ACATCC','ACAGAA','ACAGAG','ACAGAC','ACAGTA','ACAGTG','ACAGTC','ACAGGA','ACAGGT','ACAGGG','ACAGGC','ACAGCA','ACAGCG','ACAGCC','ACACAA','ACACAG','ACACAC','ACACTA','ACACTG','ACACTC','ACACGA','ACACGT','ACACGG','ACACGC','ACACCA','ACACCG','ACACCC','ACTAAA','ACTAAG','ACTAAC','ACTATA','ACTATG','ACTATC','ACTAGA','ACTAGT','ACTAGG','ACTAGC','ACTACA','ACTACG','ACTACC','ACTTAA','ACTTAG','ACTTAC','ACTTTA','ACTTTG','ACTTTC','ACTTGA','ACTTGG','ACTTGC','ACTTCA','ACTTCG','ACTTCC','ACTGAA','ACTGAG','ACTGAC','ACTGTA','ACTGTG','ACTGTC','ACTGGA','ACTGGT','ACTGGG','ACTGGC','ACTGCA','ACTGCG','ACTGCC','ACTCAA','ACTCAG','ACTCAC','ACTCTA','ACTCTG','ACTCTC','ACTCGA','ACTCGT','ACTCGG','ACTCGC','ACTCCA','ACTCCG','ACTCCC','ACGAAA','ACGAAG','ACGAAC','ACGATA','ACGATG','ACGATC','ACGAGA','ACGAGG','ACGAGC','ACGACA','ACGACG','ACGACC','ACGTAA','ACGTAG','ACGTAC','ACGTTA','ACGTTG','ACGTTC','ACGTGA','ACGTGG','ACGTGC','ACGTCA','ACGTCG','ACGTCC','ACGGAA','ACGGAG','ACGGAC','ACGGTA','ACGGTG','ACGGTC','ACGGGA','ACGGGT','ACGGGG','ACGGGC','ACGGCA','ACGGCG','ACGGCC','ACGCAA','ACGCAG','ACGCAC','ACGCTA','ACGCTG','ACGCTC','ACGCGA','ACGCGT','ACGCGG','ACGCGC','ACGCCA','ACGCCG','ACGCCC','ACCAAA','ACCAAG','ACCAAC','ACCATA','ACCATG','ACCATC','ACCAGA','ACCAGG','ACCAGC','ACCACA','ACCACG','ACCACC','ACCTAA','ACCTAG','ACCTAC','ACCTTA','ACCTTG','ACCTTC','ACCTGA','ACCTGG','ACCTGC','ACCTCA','ACCTCG','ACCTCC','ACCGAA','ACCGAG','ACCGAC','ACCGTA','ACCGTG','ACCGTC','ACCGGA','ACCGGT','ACCGGG','ACCGGC','ACCGCA','ACCGCG','ACCGCC','ACCCAA','ACCCAG','ACCCAC','ACCCTA','ACCCTG','ACCCTC','ACCCGA','ACCCGG','ACCCGC','ACCCCA','ACCCCG','ACCCCC','TAAAAA','TAAAAG','TAAAAC','TAAATA','TAAATG','TAAATC','TAAAGA','TAAAGG','TAAAGC','TAAACA','TAAACG','TAAACC','TAATAA','TAATAG','TAATAC','TAATTA','TAATTG','TAATTC','TAATGA','TAATGG','TAATGC','TAATCA','TAATCG','TAATCC','TAAGAA','TAAGAG','TAAGAC','TAAGTA','TAAGTG','TAAGTC','TAAGGA','TAAGGG','TAAGGC','TAAGCA','TAAGCG','TAAGCC','TAACAA','TAACAG','TAACAC','TAACTA','TAACTG','TAACTC','TAACGA','TAACGG','TAACGC','TAACCA','TAACCG','TAACCC','TATAAA','TATAAG','TATAAC','TATATA','TATATG','TATATC','TATAGA','TATAGG','TATAGC','TATACA','TATACG','TATACC','TATTAA','TATTAG','TATTAC','TATTTG','TATTTC','TATTGA','TATTGG','TATTGC','TATTCA','TATTCG','TATTCC','TATGAA','TATGAG','TATGAC','TATGTA','TATGTG','TATGTC','TATGGA','TATGGG','TATGGC','TATGCA','TATGCG','TATGCC','TATCAA','TATCAG','TATCAC','TATCTA','TATCTG','TATCTC','TATCGA','TATCGG','TATCGC','TATCCA','TATCCG','TATCCC','TAGAAA','TAGAAG','TAGAAC','TAGATG','TAGATC','TAGAGA','TAGAGG','TAGAGC','TAGACA','TAGACG','TAGACC','TAGTAA','TAGTAG','TAGTAC','TAGTTG','TAGTTC','TAGTGA','TAGTGG','TAGTGC','TAGTCA','TAGTCG','TAGTCC','TAGGAA','TAGGAG','TAGGAC','TAGGTA','TAGGTG','TAGGTC','TAGGGA','TAGGGG','TAGGGC','TAGGCA','TAGGCG','TAGGCC','TAGCAA','TAGCAG','TAGCAC','TAGCTA','TAGCTG','TAGCTC','TAGCGA','TAGCGG','TAGCGC','TAGCCA','TAGCCG','TAGCCC','TACAAA','TACAAG','TACAAC','TACATG','TACATC','TACAGA','TACAGG','TACAGC','TACACA','TACACG','TACACC','TACTAA','TACTAG','TACTAC','TACTTG','TACTTC','TACTGA','TACTGG','TACTGC','TACTCA','TACTCG','TACTCC','TACGAA','TACGAG','TACGAC','TACGTA','TACGTG','TACGTC','TACGGA','TACGGG','TACGGC','TACGCA','TACGCG','TACGCC','TACCAA','TACCAG','TACCAC','TACCTG','TACCTC','TACCGA','TACCGG','TACCGC','TACCCA','TACCCG','TACCCC','TTAAAA','TTAAAG','TTAAAC','TTAATG','TTAATC','TTAAGA','TTAAGG','TTAAGC','TTAACA','TTAACG','TTAACC','TTATAA','TTATAG','TTATAC','TTATTG','TTATTC','TTATGA','TTATGG','TTATGC','TTATCA','TTATCG','TTATCC','TTAGAA','TTAGAG','TTAGAC','TTAGTG','TTAGTC','TTAGGA','TTAGGG','TTAGGC','TTAGCA','TTAGCG','TTAGCC','TTACAA','TTACAG','TTACAC','TTACTG','TTACTC','TTACGA','TTACGG','TTACGC','TTACCA','TTACCG','TTACCC','TTTAAA','TTTAAG','TTTAAC','TTTATG','TTTATC','TTTAGA','TTTAGG','TTTAGC','TTTACA','TTTACG','TTTACC','TTTTAG','TTTTAC','TTTTTG','TTTTTC','TTTTGA','TTTTGG','TTTTGC','TTTTCA','TTTTCG','TTTTCC','TTTGAA','TTTGAG','TTTGAC','TTTGTG','TTTGTC','TTTGGA','TTTGGG','TTTGGC','TTTGCA','TTTGCG','TTTGCC','TTTCAA','TTTCAG','TTTCAC','TTTCTG','TTTCTC','TTTCGA','TTTCGG','TTTCGC','TTTCCA','TTTCCG','TTTCCC','TTGAAG','TTGAAC','TTGATG','TTGATC','TTGAGA','TTGAGG','TTGAGC','TTGACA','TTGACG','TTGACC','TTGTAG','TTGTAC','TTGTTG','TTGTTC','TTGTGA','TTGTGG','TTGTGC','TTGTCA','TTGTCG','TTGTCC','TTGGAA','TTGGAG','TTGGAC','TTGGTG','TTGGTC','TTGGGA','TTGGGG','TTGGGC','TTGGCA','TTGGCG','TTGGCC','TTGCAA','TTGCAG','TTGCAC','TTGCTG','TTGCTC','TTGCGA','TTGCGG','TTGCGC','TTGCCA','TTGCCG','TTGCCC','TTCAAG','TTCAAC','TTCATG','TTCATC','TTCAGA','TTCAGG','TTCAGC','TTCACA','TTCACG','TTCACC','TTCTAG','TTCTAC','TTCTTG','TTCTTC','TTCTGA','TTCTGG','TTCTGC','TTCTCA','TTCTCG','TTCTCC','TTCGAA','TTCGAG','TTCGAC','TTCGTG','TTCGTC','TTCGGA','TTCGGG','TTCGGC','TTCGCA','TTCGCG','TTCGCC','TTCCAG','TTCCAC','TTCCTG','TTCCTC','TTCCGA','TTCCGG','TTCCGC','TTCCCA','TTCCCG','TTCCCC','TGAAAG','TGAAAC','TGAATG','TGAATC','TGAAGA','TGAAGG','TGAAGC','TGAACA','TGAACG','TGAACC','TGATAG','TGATAC','TGATTG','TGATTC','TGATGA','TGATGG','TGATGC','TGATCA','TGATCG','TGATCC','TGAGAG','TGAGAC','TGAGTG','TGAGTC','TGAGGA','TGAGGG','TGAGGC','TGAGCA','TGAGCG','TGAGCC','TGACAG','TGACAC','TGACTG','TGACTC','TGACGA','TGACGG','TGACGC','TGACCA','TGACCG','TGACCC','TGTAAG','TGTAAC','TGTATG','TGTATC','TGTAGA','TGTAGG','TGTAGC','TGTACA','TGTACG','TGTACC','TGTTAG','TGTTAC','TGTTTG','TGTTTC','TGTTGA','TGTTGG','TGTTGC','TGTTCG','TGTTCC','TGTGAG','TGTGAC','TGTGTG','TGTGTC','TGTGGA','TGTGGG','TGTGGC','TGTGCA','TGTGCG','TGTGCC','TGTCAG','TGTCAC','TGTCTG','TGTCTC','TGTCGA','TGTCGG','TGTCGC','TGTCCA','TGTCCG','TGTCCC','TGGAAG','TGGAAC','TGGATG','TGGATC','TGGAGA','TGGAGG','TGGAGC','TGGACG','TGGACC','TGGTAG','TGGTAC','TGGTTG','TGGTTC','TGGTGA','TGGTGG','TGGTGC','TGGTCG','TGGTCC','TGGGAG','TGGGAC','TGGGTG','TGGGTC','TGGGGA','TGGGGG','TGGGGC','TGGGCA','TGGGCG','TGGGCC','TGGCAG','TGGCAC','TGGCTG','TGGCTC','TGGCGA','TGGCGG','TGGCGC','TGGCCA','TGGCCG','TGGCCC','TGCAAG','TGCAAC','TGCATG','TGCATC','TGCAGA','TGCAGG','TGCAGC','TGCACG','TGCACC','TGCTAG','TGCTAC','TGCTTG','TGCTTC','TGCTGA','TGCTGG','TGCTGC','TGCTCG','TGCTCC','TGCGAG','TGCGAC','TGCGTG','TGCGTC','TGCGGA','TGCGGG','TGCGGC','TGCGCA','TGCGCG','TGCGCC','TGCCAG','TGCCAC','TGCCTG','TGCCTC','TGCCGA','TGCCGG','TGCCGC','TGCCCG','TGCCCC','TCAAAG','TCAAAC','TCAATG','TCAATC','TCAAGA','TCAAGG','TCAAGC','TCAACG','TCAACC','TCATAG','TCATAC','TCATTG','TCATTC','TCATGA','TCATGG','TCATGC','TCATCG','TCATCC','TCAGAG','TCAGAC','TCAGTG','TCAGTC','TCAGGA','TCAGGG','TCAGGC','TCAGCG','TCAGCC','TCACAG','TCACAC','TCACTG','TCACTC','TCACGA','TCACGG','TCACGC','TCACCG','TCACCC','TCTAAG','TCTAAC','TCTATG','TCTATC','TCTAGA','TCTAGG','TCTAGC','TCTACG','TCTACC','TCTTAG','TCTTAC','TCTTTG','TCTTTC','TCTTGG','TCTTGC','TCTTCG','TCTTCC','TCTGAG','TCTGAC','TCTGTG','TCTGTC','TCTGGA','TCTGGG','TCTGGC','TCTGCG','TCTGCC','TCTCAG','TCTCAC','TCTCTG','TCTCTC','TCTCGA','TCTCGG','TCTCGC','TCTCCG','TCTCCC','TCGAAG','TCGAAC','TCGATG','TCGATC','TCGAGG','TCGAGC','TCGACG','TCGACC','TCGTAG','TCGTAC','TCGTTG','TCGTTC','TCGTGG','TCGTGC','TCGTCG','TCGTCC','TCGGAG','TCGGAC','TCGGTG','TCGGTC','TCGGGA','TCGGGG','TCGGGC','TCGGCG','TCGGCC','TCGCAG','TCGCAC','TCGCTG','TCGCTC','TCGCGA','TCGCGG','TCGCGC','TCGCCG','TCGCCC','TCCAAG','TCCAAC','TCCATG','TCCATC','TCCAGG','TCCAGC','TCCACG','TCCACC','TCCTAG','TCCTAC','TCCTTG','TCCTTC','TCCTGG','TCCTGC','TCCTCG','TCCTCC','TCCGAG','TCCGAC','TCCGTG','TCCGTC','TCCGGA','TCCGGG','TCCGGC','TCCGCG','TCCGCC','TCCCAG','TCCCAC','TCCCTG','TCCCTC','TCCCGG','TCCCGC','TCCCCG','TCCCCC','GAAAAG','GAAAAC','GAAATG','GAAATC','GAAAGG','GAAAGC','GAAACG','GAAACC','GAATAG','GAATAC','GAATTG','GAATTC','GAATGG','GAATGC','GAATCG','GAATCC','GAAGAG','GAAGAC','GAAGTG','GAAGTC','GAAGGG','GAAGGC','GAAGCG','GAAGCC','GAACAG','GAACAC','GAACTG','GAACTC','GAACGG','GAACGC','GAACCG','GAACCC','GATAAG','GATAAC','GATATG','GATATC','GATAGG','GATAGC','GATACG','GATACC','GATTAG','GATTAC','GATTTG','GATTGG','GATTGC','GATTCG','GATTCC','GATGAG','GATGAC','GATGTG','GATGTC','GATGGG','GATGGC','GATGCG','GATGCC','GATCAG','GATCAC','GATCTG','GATCTC','GATCGG','GATCGC','GATCCG','GATCCC','GAGAAG','GAGAAC','GAGATG','GAGAGG','GAGAGC','GAGACG','GAGACC','GAGTAG','GAGTAC','GAGTTG','GAGTGG','GAGTGC','GAGTCG','GAGTCC','GAGGAG','GAGGAC','GAGGTG','GAGGTC','GAGGGG','GAGGGC','GAGGCG','GAGGCC','GAGCAG','GAGCAC','GAGCTG','GAGCTC','GAGCGG','GAGCGC','GAGCCG','GAGCCC','GACAAG','GACAAC','GACATG','GACAGG','GACAGC','GACACG','GACACC','GACTAG','GACTAC','GACTTG','GACTGG','GACTGC','GACTCG','GACTCC','GACGAG','GACGAC','GACGTG','GACGTC','GACGGG','GACGGC','GACGCG','GACGCC','GACCAG','GACCAC','GACCTG','GACCGG','GACCGC','GACCCG','GACCCC','GTAAAG','GTAAAC','GTAATG','GTAAGG','GTAAGC','GTAACG','GTAACC','GTATAG','GTATAC','GTATTG','GTATGG','GTATGC','GTATCG','GTATCC','GTAGAG','GTAGAC','GTAGTG','GTAGGG','GTAGGC','GTAGCG','GTAGCC','GTACAG','GTACAC','GTACTG','GTACGG','GTACGC','GTACCG','GTACCC','GTTAAG','GTTAAC','GTTATG','GTTAGG','GTTAGC','GTTACG','GTTACC','GTTTAG','GTTTTG','GTTTGG','GTTTGC','GTTTCG','GTTTCC','GTTGAG','GTTGAC','GTTGTG','GTTGGG','GTTGGC','GTTGCG','GTTGCC','GTTCAG','GTTCAC','GTTCTG','GTTCGG','GTTCGC','GTTCCG','GTTCCC','GTGAAG','GTGATG','GTGAGG','GTGAGC','GTGACG','GTGACC','GTGTAG','GTGTTG','GTGTGG','GTGTGC','GTGTCG','GTGTCC','GTGGAG','GTGGAC','GTGGTG','GTGGGG','GTGGGC','GTGGCG','GTGGCC','GTGCAG','GTGCAC','GTGCTG','GTGCGG','GTGCGC','GTGCCG','GTGCCC','GTCAAG','GTCATG','GTCAGG','GTCAGC','GTCACG','GTCACC','GTCTAG','GTCTTG','GTCTGG','GTCTGC','GTCTCG','GTCTCC','GTCGAG','GTCGAC','GTCGTG','GTCGGG','GTCGGC','GTCGCG','GTCGCC','GTCCAG','GTCCTG','GTCCGG','GTCCGC','GTCCCG','GTCCCC','GGAAAG','GGAATG','GGAAGG','GGAAGC','GGAACG','GGAACC','GGATAG','GGATTG','GGATGG','GGATGC','GGATCG','GGATCC','GGAGAG','GGAGTG','GGAGGG','GGAGGC','GGAGCG','GGAGCC','GGACAG','GGACTG','GGACGG','GGACGC','GGACCG','GGACCC','GGTAAG','GGTATG','GGTAGG','GGTAGC','GGTACG','GGTACC','GGTTAG','GGTTTG','GGTTGG','GGTTGC','GGTTCG','GGTGAG','GGTGTG','GGTGGG','GGTGGC','GGTGCG','GGTGCC','GGTCAG','GGTCTG','GGTCGG','GGTCGC','GGTCCG','GGTCCC','GGGAAG','GGGATG','GGGAGG','GGGAGC','GGGACG','GGGTAG','GGGTTG','GGGTGG','GGGTGC','GGGTCG','GGGGAG','GGGGTG','GGGGGG','GGGGGC','GGGGCG','GGGGCC','GGGCAG','GGGCTG','GGGCGG','GGGCGC','GGGCCG','GGGCCC','GGCAAG','GGCATG','GGCAGG','GGCAGC','GGCACG','GGCTAG','GGCTTG','GGCTGG','GGCTGC','GGCTCG','GGCGAG','GGCGTG','GGCGGG','GGCGGC','GGCGCG','GGCGCC','GGCCAG','GGCCTG','GGCCGG','GGCCGC','GGCCCG','GCAAAG','GCAATG','GCAAGG','GCAAGC','GCAACG','GCATAG','GCATTG','GCATGG','GCATGC','GCATCG','GCAGAG','GCAGTG','GCAGGG','GCAGGC','GCAGCG','GCACAG','GCACTG','GCACGG','GCACGC','GCACCG','GCTAAG','GCTATG','GCTAGG','GCTAGC','GCTACG','GCTTAG','GCTTTG','GCTTGG','GCTTCG','GCTGAG','GCTGTG','GCTGGG','GCTGGC','GCTGCG','GCTCAG','GCTCTG','GCTCGG','GCTCGC','GCTCCG','GCGAAG','GCGATG','GCGAGG','GCGACG','GCGTAG','GCGTTG','GCGTGG','GCGTCG','GCGGAG','GCGGTG','GCGGGG','GCGGGC','GCGGCG','GCGCAG','GCGCTG','GCGCGG','GCGCGC','GCGCCG','GCCAAG','GCCATG','GCCAGG','GCCACG','GCCTAG','GCCTTG','GCCTGG','GCCTCG','GCCGAG','GCCGTG','GCCGGG','GCCGGC','GCCGCG','GCCCAG','GCCCTG','GCCCGG','GCCCCG','CAAAAG','CAAATG','CAAAGG','CAAACG','CAATAG','CAATTG','CAATGG','CAATCG','CAAGAG','CAAGTG','CAAGGG','CAAGCG','CAACAG','CAACTG','CAACGG','CAACCG','CATAAG','CATATG','CATAGG','CATACG','CATTAG','CATTGG','CATTCG','CATGAG','CATGTG','CATGGG','CATGCG','CATCAG','CATCTG','CATCGG','CATCCG','CAGAAG','CAGAGG','CAGACG','CAGTAG','CAGTGG','CAGTCG','CAGGAG','CAGGTG','CAGGGG','CAGGCG','CAGCAG','CAGCTG','CAGCGG','CAGCCG','CACAAG','CACAGG','CACACG','CACTAG','CACTGG','CACTCG','CACGAG','CACGTG','CACGGG','CACGCG','CACCAG','CACCGG','CACCCG','CTAAAG','CTAAGG','CTAACG','CTATAG','CTATGG','CTATCG','CTAGAG','CTAGGG','CTAGCG','CTACAG','CTACGG','CTACCG','CTTAAG','CTTAGG','CTTACG','CTTTGG','CTTTCG','CTTGAG','CTTGGG','CTTGCG','CTTCAG','CTTCGG','CTTCCG','CTGAGG','CTGACG','CTGTGG','CTGTCG','CTGGAG','CTGGGG','CTGGCG','CTGCAG','CTGCGG','CTGCCG','CTCAGG','CTCACG','CTCTGG','CTCTCG','CTCGAG','CTCGGG','CTCGCG','CTCCGG','CTCCCG','CGAAGG','CGAACG','CGATGG','CGATCG','CGAGGG','CGAGCG','CGACGG','CGACCG','CGTAGG','CGTACG','CGTTGG','CGTGGG','CGTGCG','CGTCGG','CGTCCG','CGGAGG','CGGTGG','CGGGGG','CGGGCG','CGGCGG','CGGCCG','CGCAGG','CGCTGG','CGCGGG','CGCGCG','CGCCGG','CCAAGG','CCATGG','CCAGGG','CCACGG','CCTAGG','CCTGGG','CCTCGG','CCGGGG','CCGCGG','CCCGGG')
#('A','T','C','G','AA','AT','AG','AC','TA','TT','TG','TC','GA','GT','GG','GC','CA','CT','CG','CC','AAA','AAT','AAG','AAC','ATA','ATT','ATG','ATC','AGA','AGT','AGG','AGC','ACA','ACT','ACG','ACC','TAA','TAT','TAG','TAC','TTA','TTT','TTG','TTC','TGA','TGT','TGG','TGC','TCA','TCT','TCG','TCC','GAA','GAT','GAG','GAC','GTA','GTT','GTG','GTC','GGA','GGT','GGG','GGC','GCA','GCT','GCG','GCC','CAA','CAT','CAG','CAC','CTA','CTT','CTG','CTC','CGA','CGT','CGG','CGC','CCA','CCT','CCG','CCC','AAAA','AAAT','AAAG','AAAC','AATA','AATT','AATG','AATC','AAGA','AAGT','AAGG','AAGC','AACA','AACT','AACG','AACC','ATAA','ATAT','ATAG','ATAC','ATTA','ATTT','ATTG','ATTC','ATGA','ATGT','ATGG','ATGC','ATCA','ATCT','ATCG','ATCC','AGAA','AGAT','AGAG','AGAC','AGTA','AGTT','AGTG','AGTC','AGGA','AGGT','AGGG','AGGC','AGCA','AGCT','AGCG','AGCC','ACAA','ACAT','ACAG','ACAC','ACTA','ACTT','ACTG','ACTC','ACGA','ACGT','ACGG','ACGC','ACCA','ACCT','ACCG','ACCC','TAAA','TAAT','TAAG','TAAC','TATA','TATT','TATG','TATC','TAGA','TAGT','TAGG','TAGC','TACA','TACT','TACG','TACC','TTAA','TTAT','TTAG','TTAC','TTTA','TTTT','TTTG','TTTC','TTGA','TTGT','TTGG','TTGC','TTCA','TTCT','TTCG','TTCC','TGAA','TGAT','TGAG','TGAC','TGTA','TGTT','TGTG','TGTC','TGGA','TGGT','TGGG','TGGC','TGCA','TGCT','TGCG','TGCC','TCAA','TCAT','TCAG','TCAC','TCTA','TCTT','TCTG','TCTC','TCGA','TCGT','TCGG','TCGC','TCCA','TCCT','TCCG','TCCC','GAAA','GAAT','GAAG','GAAC','GATA','GATT','GATG','GATC','GAGA','GAGT','GAGG','GAGC','GACA','GACT','GACG','GACC','GTAA','GTAT','GTAG','GTAC','GTTA','GTTT','GTTG','GTTC','GTGA','GTGT','GTGG','GTGC','GTCA','GTCT','GTCG','GTCC','GGAA','GGAT','GGAG','GGAC','GGTA','GGTT','GGTG','GGTC','GGGA','GGGT','GGGG','GGGC','GGCA','GGCT','GGCG','GGCC','GCAA','GCAT','GCAG','GCAC','GCTA','GCTT','GCTG','GCTC','GCGA','GCGT','GCGG','GCGC','GCCA','GCCT','GCCG','GCCC','CAAA','CAAT','CAAG','CAAC','CATA','CATT','CATG','CATC','CAGA','CAGT','CAGG','CAGC','CACA','CACT','CACG','CACC','CTAA','CTAT','CTAG','CTAC','CTTA','CTTT','CTTG','CTTC','CTGA','CTGT','CTGG','CTGC','CTCA','CTCT','CTCG','CTCC','CGAA','CGAT','CGAG','CGAC','CGTA','CGTT','CGTG','CGTC','CGGA','CGGT','CGGG','CGGC','CGCA','CGCT','CGCG','CGCC','CCAA','CCAT','CCAG','CCAC','CCTA','CCTT','CCTG','CCTC','CCGA','CCGT','CCGG','CCGC','CCCA','CCCT','CCCG','CCCC');

my $name1="";
my $seq1="";
my %counts=();
my %counts_1=();
my %counts_2=();
my %counts_3=();
my %counts_4=();
my %total_mono=();
my %total_bi=();
my %total_tri=();
my %total_tetra=();

open (IN, "<$file1") or die ("Couldn't open file $file1\n");

while (my $i=<IN>){
  next unless ($i =~ /\w+/);
  chomp($i);
  if ($i =~ /^>(\S+)/){
    unless ($seq1 eq ""){
      my $len_full=length($seq1);
      $seq1 =~ s/[^ATCG]//g;
      my $len_short=length($seq1);
      my $ratio=$len_short/$len_full;
      if ($ratio > 0.9) {
	&process_nuc($seq1, $name1);
      }
    }
    $seq1="";
    $name1=$1;
  }else{
    $seq1.=uc($i);
  }
}
close IN;
my $len_full=length($seq1);
$seq1 =~ s/[^ATCG]//g;
my $len_short=length($seq1);
my $ratio=$len_short/$len_full;
if ($ratio > 0.9) {
  process_nuc($seq1, $name1);
}

print "Matrix_";
print scalar(@array);
for (my $k=0; $k<@array; $k++){
  print "\t$array[$k]";
}print "\n";

my %norm_1=();
my %norm_2=();
my %norm_3=();
my %norm_4=();

foreach my $k (keys (%counts)){
  print "$k";

  my $value=0;
  $norm_1{'A'}=$counts_1{$k}{'A'}/$total_mono{$k};
  $norm_1{'T'}=$counts_1{$k}{'T'}/$total_mono{$k};
  $norm_1{'C'}=$counts_1{$k}{'C'}/$total_mono{$k};
  $norm_1{'G'}=$counts_1{$k}{'G'}/$total_mono{$k};

  for (my $j=0; $j<@array; $j++){
    my $eval=$array[$j];
    my @ev=split //, $eval;  
    if (length($eval)==2){
      $norm_2{$ev[0]}{$ev[1]}=$counts_2{$k}{$ev[0]}{$ev[1]}/$total_bi{$k} if ($counts_2{$k}{$ev[0]}{$ev[1]});
      $norm_2{$ev[0]}{'X'}{$ev[1]}=$counts_2{$k}{$ev[0]}{'X'}{$ev[1]}/$total_tri{$k} if ($counts_2{$k}{$ev[0]}{'X'}{$ev[1]});
      $norm_2{$ev[0]}{'X'}{'X'}{$ev[1]}=$counts_2{$k}{$ev[0]}{'X'}{'X'}{$ev[1]}/$total_tetra{$k} if ($counts_2{$k}{$ev[0]}{'X'}{'X'}{$ev[1]});
    }
    if (length($eval)==3){
      $norm_3{$ev[0]}{$ev[1]}{$ev[2]}=$counts_3{$k}{$ev[0]}{$ev[1]}{$ev[2]}/$total_tri{$k} if ($counts_3{$k}{$ev[0]}{$ev[1]}{$ev[2]});
      $norm_3{$ev[0]}{'X'}{$ev[1]}{$ev[2]}=$counts_3{$k}{$ev[0]}{'X'}{$ev[1]}{$ev[2]}/$total_tetra{$k} if ($counts_3{$k}{$ev[0]}{'X'}{$ev[1]}{$ev[2]});
      $norm_3{$ev[0]}{$ev[1]}{'X'}{$ev[2]}=$counts_3{$k}{$ev[0]}{$ev[1]}{'X'}{$ev[2]}/$total_tetra{$k} if ($counts_3{$k}{$ev[0]}{$ev[1]}{'X'}{$ev[2]});
    }
    if (length($eval)==4){
      $norm_4{$ev[0]}{$ev[1]}{$ev[2]}{$ev[3]}=$counts_4{$k}{$ev[0]}{$ev[1]}{$ev[2]}{$ev[3]}/$total_tetra{$k} if ($counts_4{$k}{$ev[0]}{$ev[1]}{$ev[2]}{$ev[3]});
    }
  }

  #print "The total mono counts are $total_mono the total bi counts are $total_bi. Freq of A: $counts_1{$k}{'A'} => $norm_1{'A'} and T: $counts_1{$k}{'T'} => $norm_1{'T'}; so di nuc AA is $counts_2{$k}{'A'}{'A'} and norm is $norm_2{'A'}{'A'}; while AT is $counts_2{$k}{'A'}{'T'} and norm is $norm_2{'A'}{'T'}\n\n\n";

  for (my $j=0; $j<@array; $j++){
    my $eval=$array[$j];
    my @ev=split //, $eval;
    if (length($eval)==1) {
      $value = sprintf("%.5f", $norm_1{$eval});
    }
    elsif (length($eval)==2){
      if ($norm_2{$ev[0]}{$ev[1]}){
	$value = sprintf("%.5f", ($norm_2{$ev[0]}{$ev[1]}/($norm_1{$ev[0]}*$norm_1{$ev[1]})));
      }else{ 
	$value = sprintf("%.5f", 0);
      }
    }elsif (length($eval)==3){
      if ($norm_3{$ev[0]}{$ev[1]}{$ev[2]}){
	$value = sprintf("%.5f", (($norm_3{$ev[0]}{$ev[1]}{$ev[2]}*$norm_1{$ev[0]}*$norm_1{$ev[1]}*$norm_1{$ev[2]})/($norm_2{$ev[0]}{$ev[1]}*$norm_2{$ev[1]}{$ev[2]}*$norm_2{$ev[0]}{'X'}{$ev[2]})));
      }else{ 
	$value = sprintf("%.5f", 0);
      }
    }elsif (length($eval)==4){
      if ($norm_4{$ev[0]}{$ev[1]}{$ev[2]}{$ev[3]}){
	$value = sprintf("%.5f", (($norm_4{$ev[0]}{$ev[1]}{$ev[2]}{$ev[3]}*$norm_2{$ev[0]}{$ev[1]}*$norm_2{$ev[0]}{'X'}{$ev[2]}*$norm_2{$ev[0]}{'X'}{'X'}{$ev[3]}*$norm_2{$ev[1]}{$ev[2]}*$norm_2{$ev[1]}{'X'}{$ev[3]}*$norm_2{$ev[2]}{$ev[3]})/($norm_3{$ev[0]}{$ev[1]}{$ev[2]}*$norm_3{$ev[1]}{$ev[2]}{$ev[3]}*$norm_3{$ev[0]}{'X'}{$ev[2]}{$ev[3]}*$norm_3{$ev[0]}{$ev[1]}{'X'}{$ev[3]}*$norm_1{$ev[0]}*$norm_1{$ev[1]}*$norm_1{$ev[2]}*$norm_1{$ev[3]})));
      }else{ 
	$value = sprintf("%.5f", 0);
      }
    }
    print "\t$value";
  }
  print "\n";
  %norm_1=();
  %norm_2=();
  %norm_3=();
  %norm_4=();
}



sub process_nuc {
  my $seq=$_[0];
  my $name= $_[1];
  my $revcomp="";
  my $mono=();
  my $bi="";
  my $tri="";
  my $tetra="";


  $total_mono{$name}+=length($seq)*2;
  $total_bi{$name}+=(length($seq)-1)*2;
  $total_tri{$name}+=(length($seq)-2)*2;
  $total_tetra{$name}+=(length($seq)-3)*2;
  $revcomp=reverse($seq);
  $revcomp=~ tr/ATCG/TAGC/;
  $counts{$name}=1;
  while ($seq){
    if (length($seq) > 3){
      $tetra=substr($seq, 0, 4);
      my @t = split //, $tetra;
      $counts_4{$name}{$t[0]}{$t[1]}{$t[2]}{$t[3]}++;
      $counts_2{$name}{$t[0]}{'X'}{'X'}{$t[3]}++;
      $counts_3{$name}{$t[0]}{'X'}{$t[2]}{$t[3]}++;
      $counts_3{$name}{$t[0]}{$t[1]}{'X'}{$t[3]}++;
      $tetra=substr($revcomp, 0, 4);
      @t = split //, $tetra;
      $counts_4{$name}{$t[0]}{$t[1]}{$t[2]}{$t[3]}++;
      $counts_2{$name}{$t[0]}{'X'}{'X'}{$t[3]}++;
      $counts_3{$name}{$t[0]}{'X'}{$t[2]}{$t[3]}++;
      $counts_3{$name}{$t[0]}{$t[1]}{'X'}{$t[3]}++;
    }
    if (length($seq) > 2){
      $tri=substr($seq, 0, 3);
      my @tr = split //, $tri;
      $counts_3{$name}{$tr[0]}{$tr[1]}{$tr[2]}++;
      $counts_2{$name}{$tr[0]}{'X'}{$tr[2]}++;
      $tri=substr($revcomp, 0, 3);
      @tr = split //, $tri;
      $counts_3{$name}{$tr[0]}{$tr[1]}{$tr[2]}++;
      $counts_2{$name}{$tr[0]}{'X'}{$tr[2]}++;
    }
    if (length($seq) > 1){
      $bi=substr($seq, 0, 2);
      my @b=split //, $bi; 
      $counts_2{$name}{$b[0]}{$b[1]}++;
      $bi=substr($revcomp, 0, 2);
      @b=split //, $bi; 
      $counts_2{$name}{$b[0]}{$b[1]}++;
    }
    $mono= substr $seq, 0, 1 , ""; 
    $counts_1{$name}{$mono}++;
    $mono= substr $revcomp, 0, 1 , ""; 
    $counts_1{$name}{$mono}++;
  }
  return 1;
}
